"use client";
import { useTransition } from "react";
import { retrySubmissionNotification, updateSubmissionStatus } from "@/features/submissions/actions";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

function formatSubmissionDate(value: Date | string) {
  return new Intl.DateTimeFormat("en-GB", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(value));
}
type Submission = { id: string; formKey: string; locale: string; status: string; notificationStatus: string; notificationError: string | null; createdAt: Date | string; payloadJson: unknown; attachments: Array<{ id: string; originalFilename: string; sizeBytes: number }> };
export function SubmissionDetail({ submission, ar }: { submission: Submission; ar: boolean }) {
  const [pending, startTransition] = useTransition();
  const payload = submission.payloadJson && typeof submission.payloadJson === "object" ? submission.payloadJson as Record<string, unknown> : {};
  return <div className="space-y-6"><Card><CardHeader><CardTitle>{submission.formKey} #{submission.id}</CardTitle><p className="text-sm text-muted-foreground">{formatSubmissionDate(submission.createdAt)} · {submission.locale}</p></CardHeader><CardContent className="space-y-4"><label className="flex items-center gap-3 text-sm font-medium">{ar ? "الحالة" : "Status"}<select value={submission.status} disabled={pending} onChange={(e) => startTransition(() => { void updateSubmissionStatus(submission.id, e.target.value); })} className="rounded-md border bg-background px-3 py-2"><option value="new">New</option><option value="in_review">In review</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="archived">Archived</option></select></label><div className="divide-y rounded-lg border">{Object.entries(payload).map(([key, value]) => <div key={key} className="grid gap-1 p-3 sm:grid-cols-[180px_1fr]"><strong>{key}</strong><span className="break-words text-muted-foreground">{Array.isArray(value) ? value.join(", ") : String(value ?? "")}</span></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>{ar ? "الإشعار" : "Notification"}</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-3"><span className="text-sm text-muted-foreground">{submission.notificationStatus}{submission.notificationError ? `: ${submission.notificationError}` : ""}</span>{submission.notificationStatus === "failed" && <Button disabled={pending} onClick={() => startTransition(() => { void retrySubmissionNotification(submission.id); })}>{ar ? "إعادة المحاولة" : "Retry notification"}</Button>}</CardContent></Card><Card><CardHeader><CardTitle>{ar ? "المرفقات" : "Attachments"}</CardTitle></CardHeader><CardContent>{submission.attachments.length ? <ul className="space-y-2">{submission.attachments.map((file) => <li key={file.id}><a className="text-primary hover:underline" href={`/api/submissions/attachments/${file.id}`} download>{file.originalFilename}</a></li>)}</ul> : <span className="text-sm text-muted-foreground">{ar ? "لا توجد مرفقات" : "No attachments"}</span>}</CardContent></Card></div>;
}
