import { AlertCircle } from "lucide-react";
import { cookies } from "next/headers";
import { FormEditor } from "@/components/dashboard/form-editor";
import { getForm, listForms } from "@/features/forms/queries";
import type { FormRendererKey } from "@/features/forms/registry-core";
export const dynamic = "force-dynamic";
type Props = { params: Promise<{ id: string }> };
type Loaded = { form: Awaited<ReturnType<typeof listForms>>[number]; ar: Awaited<ReturnType<typeof getForm>>; en: Awaited<ReturnType<typeof getForm>>; arp: Awaited<ReturnType<typeof getForm>>; enp: Awaited<ReturnType<typeof getForm>> };
async function load(id: string): Promise<Loaded | null> { const forms = await listForms(); const form = forms.find(item => item.id === id); if (!form) return null; const [ar, en, arp, enp] = await Promise.all([getForm(id, "ar"), getForm(id, "en"), getForm(id, "ar", "published"), getForm(id, "en", "published")]); return { form, ar, en, arp, enp }; }
export default async function FormEditorRoute({ params }: Props) { const { id } = await params; const ar = (await cookies()).get("dashboard-locale")?.value === "ar"; if (!/^[1-9]\d*$/.test(id)) return <ErrorBox message={ar ? "معرّف النموذج غير صالح." : "Invalid form ID."} />; let data: Loaded | null = null; let detail: string | undefined; try { data = await load(id); } catch (error) { console.error(`[dashboard/forms/${id}]`, error); detail = error instanceof Error ? error.message : undefined; } if (detail) return <ErrorBox message={ar ? "تعذر تحميل محرر النموذج." : "The form editor could not be loaded."} detail={detail} />; if (!data) return <ErrorBox message={ar ? "النموذج المطلوب غير موجود." : "The requested form was not found."} />; return <FormEditor formId={id} formKey={data.form.formKey} rendererKey={data.form.rendererKey as FormRendererKey} kind={data.form.kind} references={data.ar?.references ?? data.en?.references ?? []} locales={{ ar: toLocale(data.ar, data.arp), en: toLocale(data.en, data.enp) }} />; }
function toLocale(value: Awaited<ReturnType<typeof getForm>>, published: Awaited<ReturnType<typeof getForm>>) { return value ? { config: value.revision.config, normalized: value.revision.normalized, publishedConfig: published?.revision.config ?? null, revisionToken: value.revision.id } : null; }
function ErrorBox({ message, detail }: { message: string; detail?: string }) { return <main className="mx-auto max-w-3xl p-10 text-center" dir="auto"><AlertCircle className="mx-auto text-destructive" /><h1 className="mt-3 font-semibold">{message}</h1>{process.env.NODE_ENV === "development" && detail && <p className="mt-2 break-all text-xs text-destructive">{detail}</p>}</main>; }
